spring:
    datasource:
        url: jdbc:mysql://192.168.100.90:3306/mark_waveform_platform?useUnicode=true&characterEncoding=utf8
        username: root
        password: xinmei365
        driver-class-name: com.mysql.jdbc.Driver
        hikari:
            maximum-pool-size: 15
    data:
        elasticsearch:
            cluster-name: elasticsearch
            cluster-nodes: 192.168.100.90:9300
            repositories:
              enabled: true

#mybatis
mybatis:
    mapper-locations: classpath:mybatis/*.xml
    type-aliases-package: com.kikakeyboard.waveform
    config-location: classpath:spring/mybatis.xml













